-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Asiakas CASCADE;
DROP TABLE IF EXISTS Laakari CASCADE;
DROP TABLE IF EXISTS Tilaus CASCADE;
DROP TABLE IF EXISTS Kaynti CASCADE;
DROP TABLE IF EXISTS Hoitoohje CASCADE;
DROP TABLE IF EXISTS Raportti CASCADE;